# ===============================
# SERVER
# ===============================
server:
 port: 8181
# 
 # ===============================
# DATABASE & JPA
# ===============================
#spring:
# datasource: 
#  driver-class-name: com.mysql.cj.jdbc.Driver
#  url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
#  username: ${RDS_USERNAME}
#  password: ${RDS_PASSWORD}
# jpa:
#  show-sql: true
#  hibernate:
#    ddl-auto: update
#  properties: 
#   hibernate:
#    dialect: org.hibernate.dialect.MySQL5Dialect
# 
#  
#  
#spring:
# datasource:
#  url: jdbc:mysql://staronedb.ck6ksuvkknz5.us-east-2.rds.amazonaws.com/staronedb
#  username: root
#  password: Mysql2030
# jpa:
#  show-sql: true
#  hibernate:
#    ddl-auto: update
#  properties: 
#   hibernate:
#    dialect: org.hibernate.dialect.MySQL5Dialect
  
